[project]
authors = ["IRIS-HEP"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "analysis-grand-challenge"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "1.4.0"

[tasks]

[dependencies]
python = ">=3.7"
notebook = ">=7.2.2"
jupyterlab = ">=4.2.5"
pixi-kernel = ">=0.5.1"
ipykernel = ">=6.29.5"
pre-commit = ">=4.0.1"
jupytext = ">=1.16.4"

[pypi-dependencies]
servicex = ">=3.0.0"

[feature.latest.dependencies]
cabinetry = ">=0.6.0"
scikit-learn = ">=1.0"
xgboost = ">=1.0"
coffea = ">=2024.9.0"

[feature.cms-open-data-ttbar.tasks]
start = "jupyter lab"

# Note: This is global as using '--user'
install-ipykernel = """
python -m ipykernel install --user --name="cms-open-data-ttbar" --display-name="cms-open-data-ttbar"
"""

[feature.cms-open-data-ttbar.dependencies]
vector = ">=1.5.2"
cabinetry = ">=0.6.0"
scikit-learn = ">=1.0"
# coffea-casa restrictions
python = ">=3.7,<3.10"
coffea = ">=0.7.22,<1.0"
xgboost = ">=1.0,<1.8"
dask = "2023.11.0.*"
cloudpickle = "3.0.0.*"

[environments]
latest = ["latest"]
cms-open-data-ttbar = ["cms-open-data-ttbar"]
